# Generated by Django 3.2.7 on 2021-09-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
