# Generated by Django 3.2.7 on 2021-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='test',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
