# Generated by Django 3.2.7 on 2021-09-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='test',
        ),
    ]
