# Generated by Django 3.2.7 on 2021-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='0', max_length=200)),
                ('team_a', models.CharField(default='0', max_length=200)),
                ('team_b', models.CharField(default='0', max_length=200)),
                ('details', models.CharField(default='0', max_length=200)),
                ('private', models.BooleanField(default=True)),
                ('league', models.CharField(default='0', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('game', models.CharField(default='0', max_length=200)),
                ('game_id', models.CharField(default='0', max_length=200)),
                ('date', models.CharField(default='0', max_length=200)),
                ('sport_type', models.CharField(default='0', max_length=200)),
                ('time_stamp', models.CharField(default='0', max_length=200)),
                ('contract_address', models.CharField(default='0', max_length=200)),
                ('ratio', models.CharField(default='0', max_length=200)),
                ('mivValuePerParticipant', models.PositiveIntegerField(default=0)),
                ('minBudgetToStartContract', models.PositiveIntegerField(default=0)),
                ('creatorBudget', models.PositiveIntegerField(default=0)),
                ('creatorGuess', models.PositiveIntegerField(default=0)),
                ('participantMaxPossibleBudget', models.PositiveIntegerField(default=0)),
                ('wallet_address', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserToBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=200)),
                ('bet_uuid', models.CharField(max_length=200)),
            ],
        ),
    ]
