# Generated by Django 3.2.7 on 2021-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20210914_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='winner',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
